# ================== prod (?? 50030) ==================
spring.profiles.active=prod

app.base=/volume1/cert-data/Crawling/Certificate
public.root=/volume1/cert-data/chansol_api

python.path=/usr/bin/python3
python.args=-X utf8

public.script=/volume1/cert-data/Crawling/Certificate/Engine/public_cert_api/run_public.py
engine.script=/volume1/cert-data/Crawling/Certificate/Engine/run_once.py
engine.config=/volume1/cert-data/Crawling/Certificate/Engine/private-cert-crawl/configs/cert_map.yaml

cert.json.root=/volume1/cert-data/Crawling/Certificate/Spring/src/main/resources/json

logging.level.kr.yuhancert=INFO
